pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCOUNT_ID = '534315511736'

        FRONTEND_REPO = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/inlook-frontend"
        BACKEND_REPO  = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/inlook-backend"

        ECS_CLUSTER = 'inlook-ecs-cluster'
        ECS_SERVICE = 'inlook-service'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                sh 'docker build -t inlook-frontend ./app/frontend'
            }
        }

        stage('Build Backend Docker Image') {
            steps {
                sh 'docker build -t inlook-backend ./app/backend'
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag Docker Images') {
            steps {
                sh '''
                docker tag inlook-frontend:latest $FRONTEND_REPO:latest
                docker tag inlook-backend:latest $BACKEND_REPO:latest
                '''
            }
        }

        stage('Push Docker Images to ECR') {
            steps {
                sh '''
                docker push $FRONTEND_REPO:latest
                docker push $BACKEND_REPO:latest
                '''
            }
        }

        stage('Deploy to ECS') {
            steps {
                sh '''
                aws ecs update-service \
                  --cluster $ECS_CLUSTER \
                  --service $ECS_SERVICE \
                  --force-new-deployment
                '''
            }
        }
    }
}